name: proplink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cube: ^0.1.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  # panorama: ^0.4.1
  shared_preferences: ^2.2.2
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/json/


